const DATA = {
  // ========== 版本 ==========
  version: "1.0.0",
  // ========== 货币配置 ==========
  currency: {
    maxCarry: 999999,
  },
  // ========== 背包配置 ==========
  inventory: {
    perGatekeeperBonus: 20,
    stackLimits: {
      gold: 9999,
      basic: 99,
      rare: 1,
    },
  },
  // ========== 经验锁提示 ==========
  expLockMessages: {
    20: "去找村长谈谈，或许他知道如何让你变得更强。",
    40: "灰烬山脉的守夜人在等你。",
    60: "机械守卫守护着通往更深处的道路。",
    80: "隐修者掌握着最后的秘密。",
    99: "你已到达力量的巅峰。",
  },
  // ========== NPC定义 ==========
  npcs: {
    // 可招募随从
    ailin: { name: "艾琳", class: "ranger", recruit: true, desc: "背着父亲旧弓的邻家少女，是你出发的理由。" },
    warrior_apprentice: { name: "铁匠学徒", class: "warrior", recruit: true, desc: "老铁匠的学徒，想跟你出去见见世面。" },
    mage_apprentice: { name: "炼金学徒", class: "mage", recruit: true, desc: "炼金铺的学徒，对外面的世界充满好奇。" },
    warrior_comp: { name: "战士随从", class: "warrior", recruit: true },
    ranger_comp: { name: "游侠随从", class: "ranger", recruit: true },
    mage_comp: { name: "法师随从", class: "mage", recruit: true },
    // 场景NPC
    tavern_keeper: { name: "酒馆老板", desc: "麦酒和烤肉的香气从他身后传来。" },
    blacksmith_old: { name: "老铁匠", desc: "叮叮当当的打铁声不绝于耳。" },
    alchemist: { name: "炼金师", desc: "瓶中冒着奇异的紫色烟雾。" },
    merchant: { name: "杂货商", desc: "货架上摆满了各种日用杂货。" },
    village_chief: { name: "村长", desc: "看着你长大的老人，守着你父母托付的承诺。" },
  },
  // ========== 六维属性定义 ==========
  attributes: {
    str: { name: "力量", desc: "物理伤害", perPoint: { physAtk: 2, physDef: 1 } },
    agi: { name: "敏捷", desc: "命中/闪避/速度", perPoint: { hit: 1.5, dodge: 1, speed: 0.8 } },
    int: { name: "智力", desc: "法术伤害/治疗", perPoint: { magAtk: 2, magDef: 1 } },
    vit: { name: "体质", desc: "总血量", perPoint: { hp: 10, hpRegen: 0.3 } },
    ten: { name: "坚韧", desc: "全防御", perPoint: { allDef: 3, tenacity: 1 } },
    spi: { name: "精神", desc: "法力", perPoint: { mp: 5, magDef: 2 } },
  },
  // ========== 职业系统 ==========
  classes: {
    warrior: {
      name: "战士",
      tiers: ["见习战士", "战士", "精锐战士", "战神"],
      coreAttr: ["str", "vit"],
      dmgType: "physical",
      armor: ["cloth", "leather", "mail", "plate"],
      weapons: ["sword", "axe", "hammer", "shield"],
      skills: {
        20: ["盾墙", "猛击"],
        40: ["战吼", "破甲斩"],
        60: ["铁壁", "处决"],
        80: ["战神降临"],
      },
    },
    ranger: {
      name: "游侠",
      tiers: ["见习游侠", "游侠", "精锐游侠", "风行者"],
      coreAttr: ["agi"],
      dmgType: "physical",
      armor: ["cloth", "leather", "mail"],
      weapons: ["bow", "crossbow", "dagger"],
      skills: {
        20: ["连射", "减速箭"],
        40: ["穿透箭", "连环射击"],
        60: ["狙击", "箭雨"],
        80: ["风行者"],
      },
    },
    mage: {
      name: "法师",
      tiers: ["见习法师", "法师", "大法师", "元素主宰"],
      coreAttr: ["int", "spi"],
      dmgType: "magic",
      armor: ["cloth"],
      weapons: ["staff", "wand"],
      branches: {
        fire: { name: "火焰", dmgType: "fire", skills: { 20: ["火球"], 40: ["火焰风暴"], 60: ["陨石"], 80: ["元素主宰·火"] } },
        frost: { name: "冰霜", dmgType: "frost", skills: { 20: ["冰箭"], 40: ["冰霜新星"], 60: ["暴风雪"], 80: ["元素主宰·冰"] } },
        lightning: { name: "雷电", dmgType: "lightning", skills: { 20: ["雷击"], 40: ["连锁闪电"], 60: ["天雷"], 80: ["元素主宰·雷"] } },
        heal: { name: "治疗", dmgType: null, skills: { 20: ["治疗术"], 40: ["群体治疗"], 60: ["净化", "护盾"], 80: ["元素主宰·愈"] } },
      },
    },
  },
  // ========== 伤害类型 ==========
  damageTypes: {
    physical: { name: "物理", status: "bleed", statusName: "流血", statusDesc: "每回合损失攻击力×0.3生命，持续3回合", duration: 3, stackable: false },
    fire: { name: "火焰", status: "burn", statusName: "灼烧", statusDesc: "每回合损失攻击力×0.4生命，持续3回合", duration: 3, stackable: true, maxStacks: 2 },
    frost: { name: "冰霜", status: "slow", statusName: "减速", statusDesc: "技能冷却+1回合，持续2回合", duration: 2, stackable: false },
    lightning: { name: "雷电", status: "stun", statusName: "僵直", statusDesc: "速度-30%，持续1回合", duration: 1, stackable: false },
  },
  // ========== 装备颜色定义 ==========
  rarity: {
    white:  { name: "白色", tier: 0, minAffixes: 0, maxAffixes: 0, color: "#cccccc" },
    green:  { name: "绿色", tier: 1, minAffixes: 1, maxAffixes: 2, color: "#4caf50" },
    blue:   { name: "蓝色", tier: 2, minAffixes: 2, maxAffixes: 3, color: "#2196f3" },
    purple: { name: "紫色", tier: 3, minAffixes: 3, maxAffixes: 4, color: "#9c27b0" },
    orange: { name: "橙色", tier: 4, minAffixes: 4, maxAffixes: 5, color: "#ff9800" },
    red:    { name: "红色", tier: 5, minAffixes: 6, maxAffixes: 6, color: "#f44336" },
    gold:   { name: "金色", tier: 6, minAffixes: 3, maxAffixes: 3, color: "#ffd700" }, // 传家宝专用
  },
  // ========== 装备承载上限 ==========
  equipLimits: [
    { levelRange: [1, 20],   maxRarity: "blue",   sameColorMax: 2 },
    { levelRange: [21, 40], maxRarity: "purple", sameColorMax: 2 },
    { levelRange: [41, 60], maxRarity: "orange", sameColorMax: 2 },
    { levelRange: [61, 80], maxRarity: "red",    sameColorMax: 2 },
    { levelRange: [81, 99], maxRarity: "red",    sameColorMax: 99 },
  ],
  // ========== 装备槽位 ==========
  equipSlots: [
    "weapon", "offhand", "helmet", "chest", "legs",
    "boots", "gloves", "necklace", "ring1", "ring2",
  ],
  // ========== 装备类型到槽位映射 ==========
  equipTypeToSlot: {
    sword: "weapon", axe: "weapon", hammer: "weapon", bow: "weapon", staff: "weapon", dagger: "weapon", wand: "weapon", crossbow: "weapon",
    shield: "offhand",
    armor: "chest",
    helmet: "helmet",
    legs: "legs",
    boots: "boots",
    gloves: "gloves",
    necklace: "necklace",
    ring: "ring1", // 默认ring1，需特殊处理ring2
  },
  // ========== 符文之语（预留） ==========
  runewords: {},
  // ========== 装备词条池（80条·四系重构版）==========
  affixPool: {
    // 攻击类（24条）
    sharp:      { name: "锋锐",    effect: "physDmg",    value: 0.03,  minRarity: "green",  type: "attack" },
    heavy:      { name: "重击",    effect: "physDmg",    value: 0.06,  minRarity: "blue",   type: "attack" },
    shatter:    { name: "碎甲",    effect: "physDmg",    value: 0.10,  minRarity: "purple", type: "attack" },
    rend:       { name: "裂刃",    effect: "physDmg",    value: 0.15,  minRarity: "orange", type: "attack" },
    breakSteel: { name: "断钢",    effect: "physDmg",    value: 0.20,  minRarity: "red",    type: "attack" },
    flame:      { name: "烈焰",    effect: "fireDmg",    value: 0.03,  minRarity: "green",  type: "attack" },
    blaze:      { name: "焚火",    effect: "fireDmg",    value: 0.06,  minRarity: "blue",   type: "attack" },
    inferno:    { name: "烈火",    effect: "fireDmg",    value: 0.10,  minRarity: "purple", type: "attack" },
    explosion:  { name: "炎爆",    effect: "fireDmg",    value: 0.15,  minRarity: "orange", type: "attack" },
    phoenix:    { name: "凤凰",    effect: "fireDmg",    value: 0.20,  minRarity: "red",    type: "attack" },
    frostbite:  { name: "霜寒",    effect: "frostDmg",   value: 0.03,  minRarity: "green",  type: "attack" },
    winter:     { name: "凛冬",    effect: "frostDmg",   value: 0.06,  minRarity: "blue",   type: "attack" },
    iceSeal:    { name: "冰封",    effect: "frostDmg",   value: 0.10,  minRarity: "purple", type: "attack" },
    extremeCold:{ name: "极寒",    effect: "frostDmg",   value: 0.15,  minRarity: "orange", type: "attack" },
    eternalIce: { name: "永冻",    effect: "frostDmg",   value: 0.20,  minRarity: "red",    type: "attack" },
    surge:      { name: "电涌",    effect: "lightDmg",   value: 0.03,  minRarity: "green",  type: "attack" },
    thunder:    { name: "霹雳",    effect: "lightDmg",   value: 0.06,  minRarity: "blue",   type: "attack" },
    storm:      { name: "雷霆",    effect: "lightDmg",   value: 0.10,  minRarity: "purple", type: "attack" },
    judgment:   { name: "天谴",    effect: "lightDmg",   value: 0.15,  minRarity: "orange", type: "attack" },
    apocalypse: { name: "灭世",    effect: "lightDmg",   value: 0.20,  minRarity: "red",    type: "attack" },
    critRate:   { name: "暴击率",  effect: "critRate",   value: 0.03,  minRarity: "blue",   type: "attack" },
    critDmg:    { name: "暴伤",    effect: "critDmg",    value: 0.15,  minRarity: "purple", type: "attack" },
    pierce:     { name: "穿透",    effect: "pierce",     value: 0.10,  minRarity: "purple", type: "attack" },
    antiMagic:  { name: "破法",    effect: "antiMagic",  value: 0.20,  minRarity: "orange", type: "attack" },
    // 异常状态（18条）
    lacerate:   { name: "割裂",    effect: "bleedOnCrit",    value: 0.70,  minRarity: "blue",   type: "status" },
    bloodBlade: { name: "血刃",    effect: "bleedDmg",       value: 0.50,  minRarity: "purple", type: "status" },
    ember:      { name: "燃烬",    effect: "burnOnHit",      value: 0.50,  minRarity: "blue",   type: "status" },
    bodyBurn:   { name: "焚身",    effect: "burnMaxStacks",  value: 3,     minRarity: "orange", type: "status" },
    iceThorn:   { name: "冰刺",    effect: "slowOnHit",      value: 0.50,  minRarity: "blue",   type: "status" },
    coldBone:   { name: "寒骨",    effect: "frostBonusOnSlow",value: 0.30, minRarity: "purple", type: "status" },
    thunderStrike:{name:"雷击",   effect: "stunOnHit",      value: 0.40,  minRarity: "blue",   type: "status" },
    paralysis:  { name: "麻痹",    effect: "lightBonusOnStun",value:0.30, minRarity: "purple", type: "status" },
    ignite:     { name: "点燃",    effect: "fireBonusOnBurn",value: 0.25,  minRarity: "orange", type: "status" },
    rupture:    { name: "裂伤",    effect: "physBonusOnBleed",value:0.25,  minRarity: "orange", type: "status" },
    chainFlash: { name: "连锁闪",  effect: "chainTarget",    value: 1,     minRarity: "purple", type: "status" },
    frostNova:  { name: "冰霜新星",effect: "freezeAllChance",value: 0.30,  minRarity: "orange", type: "status" },
    fireExplode:{ name: "火焰爆炸",effect: "aoeOnKill",      value: 0.30,  minRarity: "orange", type: "status" },
    armorBreak: { name: "破甲斩",  effect: "reduceArmor",    value: 0.15,  minRarity: "blue",   type: "status" },
    frostSpike: { name: "霜刺",    effect: "reduceSpeed",    value: 0.20,  minRarity: "blue",   type: "status" },
    thunderShock:{name: "雷震",    effect: "reduceHit",      value: 0.20,  minRarity: "blue",   type: "status" },
    scorchedSkin:{name: "灼肤",    effect: "burnReduceAtk",  value: 0.10,  minRarity: "purple", type: "status" },
    bleedOut:   { name: "流血不止",effect: "bleedNoHeal",    value: true,  minRarity: "orange", type: "status" },
    // 速度出手（8条）
    swift:      { name: "轻快",    effect: "speed",          value: 0.03,  minRarity: "green",  type: "speed" },
    gale:       { name: "疾风",    effect: "speed",          value: 0.06,  minRarity: "blue",   type: "speed" },
    lightningFast:{name:"电光",    effect: "speed",          value: 0.10,  minRarity: "purple", type: "speed" },
    blink:      { name: "瞬影",    effect: "speed",          value: 0.15,  minRarity: "orange", type: "speed" },
    godSpeed:   { name: "神速",    effect: "speed",          value: 0.20,  minRarity: "red",    type: "speed" },
    firstStrike:{ name: "先手",    effect: "firstTurnSpeed", value: 0.30,  minRarity: "purple", type: "speed" },
    nimble:     { name: "迅捷",    effect: "speedHpTrade",   value: {spd:0.08, hp:-0.05}, minRarity: "blue", type: "speed" },
    windSpirit: { name: "风灵",    effect: "dodgeSpeed",     value: 0.20,  minRarity: "orange", type: "speed" },
    // 防御类（12条）
    steelBody:  { name: "钢躯",    effect: "physDef",        value: 0.10,  minRarity: "green",  type: "defense" },
    ironWall:   { name: "铁壁",    effect: "physDef",        value: 0.20,  minRarity: "blue",   type: "defense" },
    fortress:   { name: "堡垒",    effect: "physDef",        value: 0.30,  minRarity: "purple", type: "defense" },
    immortal:   { name: "不朽",    effect: "physDef",        value: 0.40,  minRarity: "orange", type: "defense" },
    fireResist: { name: "耐火",    effect: "fireRes",        value: 0.15,  minRarity: "green",  type: "defense" },
    frostResist:{ name: "耐寒",    effect: "frostRes",       value: 0.15,  minRarity: "green",  type: "defense" },
    lightResist:{ name: "耐雷",    effect: "lightRes",       value: 0.15,  minRarity: "green",  type: "defense" },
    elemShield: { name: "元素盾",  effect: "allElemRes",     value: 0.10,  minRarity: "blue",   type: "defense" },
    elemBarrier:{ name: "元素壁垒",effect: "allElemRes",     value: 0.20,  minRarity: "purple", type: "defense" },
    vitality:   { name: "生命",    effect: "maxHp",          value: 0.10,  minRarity: "green",  type: "defense" },
    vigor:      { name: "生机",    effect: "maxHp",          value: 0.20,  minRarity: "blue",   type: "defense" },
    regen:      { name: "再生",    effect: "hpRegen",        value: 5,     minRarity: "blue",   type: "defense" },
    // 功能类（10条）
    bloodthirst:{ name: "嗜血",    effect: "lifeSteal",      value: 0.08,  minRarity: "purple", type: "utility" },
    energyDrain:{ name: "吸能",    effect: "manaSteal",      value: 0.05,  minRarity: "purple", type: "utility" },
    warCry:     { name: "战吼",    effect: "firstTurnDmg",   value: 0.25,  minRarity: "blue",   type: "utility" },
    executioner:{ name: "处刑人",  effect: "lowHpDmg",       value: 0.30,  minRarity: "orange", type: "utility" },
    desperate:  { name: "破釜",    effect: "lowHpDmg",       value: 0.30,  minRarity: "orange", type: "utility" },
    desperate2: { name: "绝境",    effect: "veryLowHpDmg",   value: 0.60,  minRarity: "red",    type: "utility" },
    unyielding: { name: "不屈",    effect: "cheatDeathChance", value: 0.10,  minRarity: "red",    type: "utility" },
    purify:     { name: "净化",    effect: "debuffCleanse",  value: 0.30,  minRarity: "orange", type: "utility" },
    guardian:   { name: "守护之约",effect: "protectChance",  value: 0.15,  minRarity: "purple", type: "utility" },
    comrade:    { name: "战友",    effect: "companionDmg",   value: 0.10,  minRarity: "blue",   type: "utility" },
    // 稀有类（8条）
    dragonRage: { name: "龙之怒",  effect: "dragonDmg",      value: {chance:0.05, mult:3.0}, minRarity: "orange", type: "rare" },
    dragonScale:{ name: "龙之鳞",  effect: "dragonImmune",    value: 0.05,  minRarity: "orange", type: "rare" },
    dragonBreath:{name: "龙之息",  effect: "dragonFire",     value: 80,    minRarity: "orange", type: "rare" },
    divineBless:{ name: "神佑",    effect: "divineImmune",   value: true,  minRarity: "red",    type: "rare" },
    divinePunish:{name: "神罚",    effect: "divineCrit",     value: true,  minRarity: "red",    type: "rare" },
    divineSpeed:{ name: "神速·战", effect: "extraTurn",      value: true,  minRarity: "red",    type: "rare" },
    skyThunder: { name: "天雷",    effect: "skyThunder",     value: {chance:0.05, dmg:1.5}, minRarity: "red", type: "rare" },
    iceAge:     { name: "冰河",    effect: "iceAge",         value: {chance:0.05, freeze:true}, minRarity: "red", type: "rare" },
  },

  // ========== 灰烟村场景定义 ==========
  scenes: {
    greyVillage_tavern: {
      id: 'greyVillage_tavern',
      type: 'safe',
      name: '灰烟村·酒馆',
      description: '温暖的酒馆，飘着麦酒和烤肉的香气。炉火噼啪作响，艾琳坐在窗边擦拭她的弓。这是你的出生地。',
      exits: ['greyVillage', 'greyVillage_grocery', 'greyVillage_blacksmith', 'greyVillage_alchemist'],
      npcs: ['ailin', 'tavern_keeper'],
    },
    greyVillage_grocery: {
      id: 'greyVillage_grocery',
      type: 'safe',
      name: '灰烟村·杂货铺',
      description: '货架上摆满了各种日用杂货和冒险用品。老板娘米拉正清点着货物。',
      exits: ['greyVillage_tavern', 'greyVillage_wasteland'],
      npcs: ['merchant'],
      shopType: 'grocery',
    },
    greyVillage_blacksmith: {
      id: 'greyVillage_blacksmith',
      type: 'safe',
      name: '灰烟村·铁匠铺',
      description: '叮叮当当的打铁声不绝于耳，炉火映红了整个铺子。老铁匠正在锻造一把长剑，旁边站着一个年轻的学徒。',
      exits: ['greyVillage_tavern', 'greyVillage_wasteland'],
      npcs: ['blacksmith_old', 'warrior_apprentice'],
      shopType: 'blacksmith',
    },
    greyVillage_alchemist: {
      id: 'greyVillage_alchemist',
      type: 'safe',
      name: '灰烟村·炼金铺',
      description: '瓶中冒着奇异的紫色烟雾，架子上摆满了各种试剂瓶。炼金师正在调配药水，学徒在一旁记录配方。',
      exits: ['greyVillage_tavern', 'greyVillage_wasteland'],
      npcs: ['alchemist', 'mage_apprentice'],
      shopType: 'alchemist',
    },
    greyVillage_wasteland: {
      id: 'greyVillage_wasteland',
      type: 'wild',
      name: '灰烟村·荒地',
      description: '荒芜的野地，杂草丛生，几块散落的石头露在地表。野狗在远处游荡，警惕地盯着每一个靠近的生物。',
      exits: ['greyVillage_grocery', 'greyVillage_blacksmith', 'greyVillage_alchemist', 'greyVillage_bandit_path'],
      enemies: ['wild_dog', 'wild_dog', 'wild_dog', 'wild_dog', 'wild_dog', 'wild_dog'],
      level: 1,
      allowExplore: true,
    },
    greyVillage_bandit_path: {
      id: 'greyVillage_bandit_path',
      type: 'wild',
      name: '灰烟村·山后小径',
      description: '狭窄的山间小径，两侧是高耸的岩壁。空气中弥漫着危险的气息，山贼的营火在远处若隐若现。',
      exits: ['greyVillage_wasteland', 'greyVillage_cave'],
      enemies: ['bandit', 'bandit', 'bandit', 'bandit', 'bandit'],
      level: 3,
      autoCombat: true, // 进入即触发战斗
    },
    greyVillage_cave: {
      id: 'greyVillage_cave',
      type: 'dungeon',
      name: '灰烟村·山洞地下城',
      description: '幽深的洞穴中传来滴水的回响。这里曾是古代矿工的通道，如今被各种怪物占据。',
      exits: ['greyVillage_bandit_path', 'greyVillage_cave_1'],
      level: 5,
      dungeonStages: 8,
    },
    greyVillage_cave_boss: {
      id: 'greyVillage_cave_boss',
      type: 'boss',
      name: '地下城·深处祭坛',
      description: '洞穴最深处，一座古老的祭坛散发着微弱的蓝光。守护着这里的存在并不欢迎闯入者。',
      exits: ['greyVillage_cave'],
      enemies: ['cave_boss'],
      level: 8,
    },
    greyVillage_chief_house: {
      id: 'greyVillage_chief_house',
      type: 'boss',
      name: '灰烟村·村口村长家',
      description: '村长的小屋坐落在村口，门前种着两棵老槐树。村长站在门口，目光深邃地看着你。',
      exits: ['greyVillage_tavern'],
      npcs: ['village_chief'],
      enemies: ['village_chief_boss'],
      level: 15,
      gatekeeper: 'villageChief',
    },
    greyVillage: {
      id: 'greyVillage',
      type: 'safe',
      name: '灰烟村',
      description: '你长大的地方。灰烟村不大，但处处透着安宁。酒馆、铁匠铺、杂货铺、炼金铺分布在村子的主干道上。',
      exits: ['greyVillage_tavern', 'greyVillage_grocery', 'greyVillage_blacksmith', 'greyVillage_alchemist', 'greyVillage_wasteland', 'greyVillage_chief_house'],
    },
  },

  // ========== 敌人定义 ==========
  enemies: {
    wild_dog: {
      name: '野狗',
      level: 2,
      hp: 35, maxHp: 35,
      mp: 0, maxMp: 0,
      attributes: { str: 6, agi: 8, int: 3, vit: 5, ten: 4, spi: 3 },
      speed: 12,
      attack: 8,
      defense: 3,
      physAtk: 12, physDef: 3,
      magAtk: 0, magDef: 1,
      hit: 12, dodge: 8,
      critRate: 0.05, critDmg: 1.5,
      exp: 30,
      gold: 6,
      drops: [
        { item: 'dog_tooth', chance: 0.3 },
      ],
    },
    bandit: {
      name: '山贼',
      level: 4,
      hp: 60, maxHp: 60,
      mp: 10, maxMp: 10,
      attributes: { str: 10, agi: 7, int: 4, vit: 8, ten: 6, spi: 4 },
      speed: 10,
      attack: 15,
      defense: 8,
      physAtk: 20, physDef: 8,
      magAtk: 0, magDef: 3,
      hit: 10, dodge: 7,
      critRate: 0.08, critDmg: 1.6,
      exp: 60,
      gold: 15,
      drops: [
        { item: 'rusty_sword', chance: 0.15 },
        { item: 'leather_armor', chance: 0.1 },
        { item: 'healing_potion', chance: 0.2 },
      ],
    },
    cave_rat: {
      name: '洞穴巨鼠',
      level: 5,
      hp: 50, maxHp: 50,
      mp: 0, maxMp: 0,
      attributes: { str: 8, agi: 10, int: 2, vit: 6, ten: 5, spi: 2 },
      speed: 14,
      attack: 12,
      defense: 5,
      physAtk: 16, physDef: 5,
      magAtk: 0, magDef: 2,
      hit: 15, dodge: 10,
      critRate: 0.1, critDmg: 1.5,
      exp: 45,
      gold: 8,
      drops: [
        { item: 'rat_tail', chance: 0.25 },
      ],
    },
    cave_spider: {
      name: '洞穴蜘蛛',
      level: 6,
      hp: 55, maxHp: 55,
      mp: 15, maxMp: 15,
      attributes: { str: 7, agi: 12, int: 5, vit: 6, ten: 5, spi: 4 },
      speed: 16,
      attack: 14,
      defense: 4,
      physAtk: 14, physDef: 4,
      magAtk: 6, magDef: 4,
      hit: 18, dodge: 12,
      critRate: 0.12, critDmg: 1.7,
      exp: 55,
      gold: 10,
      drops: [
        { item: 'spider_silk', chance: 0.2 },
        { item: 'healing_potion', chance: 0.15 },
      ],
    },
    cave_slime: {
      name: '史莱姆',
      level: 5,
      hp: 80, maxHp: 80,
      mp: 10, maxMp: 10,
      attributes: { str: 6, agi: 4, int: 3, vit: 10, ten: 8, spi: 3 },
      speed: 6,
      attack: 10,
      defense: 12,
      physAtk: 12, physDef: 12,
      magAtk: 0, magDef: 5,
      hit: 6, dodge: 4,
      critRate: 0.02, critDmg: 1.2,
      exp: 50,
      gold: 5,
      drops: [
        { item: 'slime_gel', chance: 0.4 },
      ],
    },
    cave_skeleton: {
      name: '骷髅战士',
      level: 7,
      hp: 70, maxHp: 70,
      mp: 0, maxMp: 0,
      attributes: { str: 12, agi: 6, int: 2, vit: 7, ten: 8, spi: 2 },
      speed: 8,
      attack: 20,
      defense: 10,
      physAtk: 24, physDef: 10,
      magAtk: 0, magDef: 3,
      hit: 9, dodge: 6,
      critRate: 0.08, critDmg: 1.5,
      exp: 70,
      gold: 12,
      drops: [
        { item: 'bone_fragment', chance: 0.3 },
        { item: 'rusty_sword', chance: 0.1 },
      ],
    },
    cave_bat: {
      name: '吸血蝙蝠',
      level: 6,
      hp: 45, maxHp: 45,
      mp: 5, maxMp: 5,
      attributes: { str: 6, agi: 14, int: 3, vit: 5, ten: 4, spi: 3 },
      speed: 18,
      attack: 12,
      defense: 3,
      physAtk: 12, physDef: 3,
      magAtk: 0, magDef: 2,
      hit: 21, dodge: 14,
      critRate: 0.15, critDmg: 1.8,
      exp: 50,
      gold: 8,
      drops: [
        { item: 'bat_wing', chance: 0.25 },
      ],
    },
    cave_boss: {
      name: '洞穴守护者',
      level: 10,
      hp: 300, maxHp: 300,
      mp: 50, maxMp: 50,
      attributes: { str: 18, agi: 10, int: 8, vit: 15, ten: 12, spi: 8 },
      speed: 12,
      attack: 35,
      defense: 20,
      physAtk: 36, physDef: 20,
      magAtk: 16, magDef: 12,
      hit: 15, dodge: 10,
      critRate: 0.15, critDmg: 2.0,
      exp: 500,
      gold: 100,
      drops: [
        { item: 'cave_treasure_chest', chance: 1.0 },
      ],
      isBoss: true,
    },
    village_chief_boss: {
      name: '村长',
      level: 20,
      hp: 3000, maxHp: 3000,
      mp: 100, maxMp: 100,
      attributes: { str: 20, agi: 12, int: 15, vit: 25, ten: 20, spi: 12 },
      speed: 10,
      attack: 50,
      defense: 30,
      physAtk: 40, physDef: 30,
      magAtk: 20, magDef: 18,
      hit: 18, dodge: 12,
      critRate: 0.1, critDmg: 1.5,
      exp: 2000,
      gold: 500,
      drops: [
        { item: 'fathers_letter', chance: 1.0 },
      ],
      isBoss: true,
      isGatekeeper: true,
    },
  },

  // ========== 地下城阶段配置 ==========
  dungeonStages: {
    greyVillage_cave: [
      { enemies: ['cave_rat', 'cave_rat'], desc: '入口处，几只巨鼠在黑暗中窥视着你。' },
      { enemies: ['cave_rat', 'cave_spider'], desc: '通道变窄了，蛛网挂在岩壁上。' },
      { enemies: ['cave_spider', 'cave_spider', 'cave_rat'], desc: '蜘蛛的巢穴，地面上铺满了白色的丝。' },
      { enemies: ['cave_slime', 'cave_slime'], desc: '潮湿的洞穴，绿色的史莱姆在墙边蠕动。' },
      { enemies: ['cave_skeleton', 'cave_skeleton'], desc: '古老的矿道，骷髅战士从阴影中站起。' },
      { enemies: ['cave_bat', 'cave_bat', 'cave_bat'], desc: '深邃的洞穴中，成群的蝙蝠在头顶盘旋。' },
      { enemies: ['cave_skeleton', 'cave_spider', 'cave_slime'], desc: '洞穴深处的交汇点，各种怪物在此聚集。' },
      { enemies: ['cave_boss'], desc: '最深处，古老的祭坛前，守护者等待着挑战者。' },
    ],
  },

  // ========== 物品定义 ==========
  items: {
    // 经验丹
    exp_pill: {
      id: 'exp_pill',
      name: '经验丹',
      type: 'consumable',
      subtype: 'exp',
      rarity: 'purple',
      level: 1,
      stackable: true,
      maxStack: 99,
      expValue: 1000000,
      description: '蕴含着庞大经验的丹药，使用后获得100万经验值。',
      usableOn: ['player', 'companion'],
      price: 100,
    },
    // 药水
    healing_potion: {
      id: 'healing_potion',
      name: '生命药水',
      type: 'consumable',
      subtype: 'heal',
      rarity: 'white',
      level: 1,
      stackable: true,
      maxStack: 99,
      healHp: 50,
      description: '恢复50点生命值。',
      usableOn: ['player', 'companion'],
      price: 5,
    },
    mana_potion: {
      id: 'mana_potion',
      name: '法力药水',
      type: 'consumable',
      subtype: 'mana',
      rarity: 'white',
      level: 1,
      stackable: true,
      maxStack: 99,
      healMp: 30,
      description: '恢复30点法力值。',
      usableOn: ['player', 'companion'],
      price: 5,
    },
    advanced_healing_potion: {
      id: 'advanced_healing_potion',
      name: '高级生命药水',
      type: 'consumable',
      subtype: 'heal',
      rarity: 'green',
      level: 5,
      stackable: true,
      maxStack: 99,
      healHp: 150,
      description: '恢复150点生命值。',
      usableOn: ['player', 'companion'],
      price: 15,
    },
    advanced_mana_potion: {
      id: 'advanced_mana_potion',
      name: '高级法力药水',
      type: 'consumable',
      subtype: 'mana',
      rarity: 'green',
      level: 5,
      stackable: true,
      maxStack: 99,
      healMp: 80,
      description: '恢复80点法力值。',
      usableOn: ['player', 'companion'],
      price: 15,
    },
    // 材料
    dog_tooth: { id: 'dog_tooth', name: '狗牙', type: 'material', rarity: 'white', level: 1, stackable: true, maxStack: 99, price: 1 },
    rat_tail: { id: 'rat_tail', name: '鼠尾', type: 'material', rarity: 'white', level: 1, stackable: true, maxStack: 99, price: 1 },
    spider_silk: { id: 'spider_silk', name: '蛛丝', type: 'material', rarity: 'green', level: 1, stackable: true, maxStack: 99, price: 3 },
    slime_gel: { id: 'slime_gel', name: '史莱姆凝胶', type: 'material', rarity: 'white', level: 1, stackable: true, maxStack: 99, price: 2 },
    bone_fragment: { id: 'bone_fragment', name: '骨头碎片', type: 'material', rarity: 'white', level: 1, stackable: true, maxStack: 99, price: 2 },
    bat_wing: { id: 'bat_wing', name: '蝙蝠翅膀', type: 'material', rarity: 'green', level: 1, stackable: true, maxStack: 99, price: 3 },
    // 任务物品
    fathers_letter: { id: 'fathers_letter', name: '父亲的旧信', type: 'quest', rarity: 'gold', level: 1, description: '村长交给你的信，上面有你父亲的笔迹。' },
    cave_treasure_chest: { id: 'cave_treasure_chest', name: '洞穴宝箱', type: 'treasure', rarity: 'purple', level: 10, description: '击败洞穴守护者后获得的宝箱，里面可能有珍贵的装备。' },
    // 装备（掉落）
    rusty_sword: { id: 'rusty_sword', name: '生锈的剑', type: 'sword', rarity: 'white', level: 3, baseStats: { physAtk: 5 }, price: 5 },
    leather_armor: { id: 'leather_armor', name: '皮甲', type: 'armor', rarity: 'white', level: 3, baseStats: { physDef: 4 }, price: 5 },
  },

  // ========== 商店配置 ==========
  shops: {
    grocery: {
      name: '杂货铺',
      items: [
        { itemId: 'healing_potion', price: 5, stock: 99 },
        { itemId: 'mana_potion', price: 5, stock: 99 },
        { itemId: 'advanced_healing_potion', price: 15, stock: 50 },
        { itemId: 'advanced_mana_potion', price: 15, stock: 50 },
      ],
      buyRate: 0.5, // 收购价格为售价的50%
    },
    blacksmith: {
      name: '铁匠铺',
      forgeCost: 10, // 锻造基础费用
      enhanceCost: 20, // 强化基础费用
      services: ['forge', 'enhance', 'repair'],
    },
    alchemist: {
      name: '炼金铺',
      enchantCost: 15, // 附魔费用
      socketCost: 25, // 镶嵌费用
      services: ['enchant', 'socket'],
    },
  },

  // ========== 技能定义 ==========
  skills: {
    // 战士技能
    shield_wall: {
      name: '盾墙', type: 'active', target: 'self',
      cost: { mp: 10 }, cooldown: 3,
      effect: { physDefBoost: 0.5, duration: 2 },
      description: '提升50%物理防御，持续2回合。',
    },
    slam: {
      name: '猛击', type: 'active', target: 'enemy',
      cost: { mp: 8 }, cooldown: 2,
      effect: { dmgMultiplier: 1.8, dmgType: 'physical' },
      description: '造成180%物理伤害。',
    },
    // 游侠技能
    rapid_shot: {
      name: '连射', type: 'active', target: 'enemy',
      cost: { mp: 10 }, cooldown: 2,
      effect: { dmgMultiplier: 1.3, hits: 2, dmgType: 'physical' },
      description: '连续射击2次，每次造成130%物理伤害。',
    },
    slow_arrow: {
      name: '减速箭', type: 'active', target: 'enemy',
      cost: { mp: 8 }, cooldown: 3,
      effect: { dmgMultiplier: 1.0, dmgType: 'physical', applyStatus: 'slow', statusDuration: 2 },
      description: '造成100%物理伤害并附加减速。',
    },
    // 法师技能
    fireball: {
      name: '火球', type: 'active', target: 'enemy',
      cost: { mp: 12 }, cooldown: 2,
      effect: { dmgMultiplier: 2.0, dmgType: 'fire', applyStatus: 'burn', statusDuration: 3 },
      description: '造成200%火焰伤害，有几率附加灼烧。',
    },
    ice_arrow: {
      name: '冰箭', type: 'active', target: 'enemy',
      cost: { mp: 10 }, cooldown: 2,
      effect: { dmgMultiplier: 1.5, dmgType: 'frost', applyStatus: 'slow', statusDuration: 2 },
      description: '造成150%冰霜伤害并附加减速。',
    },
    thunder_strike: {
      name: '雷击', type: 'active', target: 'enemy',
      cost: { mp: 12 }, cooldown: 2,
      effect: { dmgMultiplier: 1.8, dmgType: 'lightning', applyStatus: 'stun', statusDuration: 1 },
      description: '造成180%雷电伤害并附加僵直。',
    },
    heal: {
      name: '治疗术', type: 'active', target: 'ally',
      cost: { mp: 10 }, cooldown: 2,
      effect: { healMultiplier: 1.5, healType: 'magAtk' },
      description: '恢复目标150%法术攻击力的生命值。',
    },
    // 通用技能
    normal_attack: {
      name: '普通攻击', type: 'active', target: 'enemy',
      cost: {}, cooldown: 0,
      effect: { dmgMultiplier: 1.0, dmgType: 'physical' },
      description: '造成100%物理伤害。',
    },
    defend: {
      name: '防御', type: 'active', target: 'self',
      cost: {}, cooldown: 0,
      effect: { physDefBoost: 0.3, duration: 1 },
      description: '提升30%物理防御，持续1回合。',
    },
  },

  // ========== 世界地图 ==========
  world: {
    zones: {
      greyVillage: {
        name: "灰烟村",
        levelRange: [1, 20],
        gatekeeper: "villageChief",
        locations: ["酒馆", "杂货铺", "铁匠铺", "炼金铺", "荒地", "山后小径", "山洞地下城", "村长家"],
        desc: "牧场起点，资源产出。你长大的地方。",
      },
      ashMountains: {
        name: "灰烬山脉",
        levelRange: [21, 40],
        gatekeeper: "nightWatcher",
        locations: ["山脚洞", "废弃仓库", "河岸洞穴", "路边坟", "旧矿道"],
        desc: "资源初级加工。通往灰烬镇的路。",
      },
      ashMines: {
        name: "灰烬矿场",
        levelRange: [41, 60],
        gatekeeper: "mechanicalGuard",
        locations: ["无底洞矿场", "旧矿镇", "归童坊", "铁矿裂隙", "机械之守殿堂"],
        desc: "资源精炼、中转。机械守卫的领地。",
      },
      newWorld: {
        name: "新世界",
        levelRange: [61, 80],
        gatekeeper: "hermit",
        locations: ["资源平原", "寂静城镇", "空置殿堂", "幽影裂隙"],
        desc: "组织所在地。资源消耗终端。",
      },
      skyTower: {
        name: "浮空塔",
        levelRange: [81, 99],
        gatekeeper: "finalBoss",
        subZones: {
          outerCourt:  { name: "外庭",   levelRange: [81, 85], locations: ["81-85级野外帧"] },
          corridor:    { name: "回廊",   levelRange: [86, 90], locations: ["86-90级野外帧", "组织档案馆"] },
          innerCourt:  { name: "内庭",   levelRange: [91, 95], locations: ["91-95级野外帧", "组织演武场"] },
          throneHall:  { name: "至高殿", levelRange: [96, 99], locations: ["终局Boss房"] },
        },
        desc: "总部。主人的餐桌。",
      },
    },
  },
  // ========== 守门员 ==========
  gatekeepers: {
    villageChief: {
      name: "村长",
      level: 20,
      knows: "父母的嘱托。不知道组织。",
      stance: "我答应过你爹娘，要让你活着。",
      combat: { hp: 3000, armor: 200, regen: 50, style: "tank" },
      reward: "父亲的旧信",
      onDefeat: "unlock_ashMountains",
    },
    nightWatcher: {
      name: "守夜人",
      level: 40,
      knows: "组织存在，是中层的执行者。",
      stance: "你普普通通过日子自然无恙，露点野心出来我就得做点什么。",
      combat: { hp: 5000, atk: 300, armor: 50, crit: 0.3, style: "glassCannon" },
      reward: "组织铭牌",
      onDefeat: "unlock_ashMines",
      foreshadow: [37, 38], // 暗杀事件等级
    },
    mechanicalGuard: {
      name: "机械守卫",
      level: 60,
      knows: "组织的守门人，中立执行者。",
      stance: "检测到未授权人员。准备排除。",
      combat: { hp: 8000, atk: 400, armor: 300, style: "mechanical" },
      reward: "机械核心",
      onDefeat: "unlock_newWorld",
    },
    hermit: {
      name: "隐修者",
      level: 80,
      knows: "组织的叛逃者，知道一切真相。",
      stance: "你终于来了。我等了很久。",
      combat: { hp: 12000, atk: 500, armor: 100, style: "mystic" },
      reward: "十二碎片之钥",
      onDefeat: "unlock_skyTower",
    },
    finalBoss: {
      name: "组织首领",
      level: 99,
      knows: "一切。",
      stance: "欢迎来到餐桌，孩子。",
      combat: { hp: 50000, atk: 800, armor: 500, style: "final" },
      reward: "真相",
      onDefeat: "game_complete",
    },
  },
};
